version: 0.2

env:
  variables:
    NONEED: "/bin/true"

phases:
  install:
    commands:
      - echo Nothing
  pre_build:
    commands:
      - echo Nothing to do in the pre_build phase...
  build:
    commands:
      - echo Build started on `date`
      - ls
      - pwd
      - bash autogen.sh
      - make
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - dgamelaunch
  discard-paths: yes
